// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcDewpoint_cpp
NumericVector calcDewpoint_cpp(NumericVector airTemp, NumericVector relativeHumidity, std::string inputunits, std::string outputunits, int roundby);
RcppExport SEXP _weathertools_calcDewpoint_cpp(SEXP airTempSEXP, SEXP relativeHumiditySEXP, SEXP inputunitsSEXP, SEXP outputunitsSEXP, SEXP roundbySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type airTemp(airTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relativeHumidity(relativeHumiditySEXP);
    Rcpp::traits::input_parameter< std::string >::type inputunits(inputunitsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputunits(outputunitsSEXP);
    Rcpp::traits::input_parameter< int >::type roundby(roundbySEXP);
    rcpp_result_gen = Rcpp::wrap(calcDewpoint_cpp(airTemp, relativeHumidity, inputunits, outputunits, roundby));
    return rcpp_result_gen;
END_RCPP
}
// calcHI_parallel
NumericVector calcHI_parallel(NumericVector airTemp, NumericVector relativeHumidity);
RcppExport SEXP _weathertools_calcHI_parallel(SEXP airTempSEXP, SEXP relativeHumiditySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type airTemp(airTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relativeHumidity(relativeHumiditySEXP);
    rcpp_result_gen = Rcpp::wrap(calcHI_parallel(airTemp, relativeHumidity));
    return rcpp_result_gen;
END_RCPP
}
// calcRH_cpp
NumericVector calcRH_cpp(NumericVector airTemp, NumericVector dewPoint, String inputunits);
RcppExport SEXP _weathertools_calcRH_cpp(SEXP airTempSEXP, SEXP dewPointSEXP, SEXP inputunitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type airTemp(airTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dewPoint(dewPointSEXP);
    Rcpp::traits::input_parameter< String >::type inputunits(inputunitsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcRH_cpp(airTemp, dewPoint, inputunits));
    return rcpp_result_gen;
END_RCPP
}
// calcRH_vpd_cpp
NumericVector calcRH_vpd_cpp(NumericVector airTemp, NumericVector vpd, String inputunits);
RcppExport SEXP _weathertools_calcRH_vpd_cpp(SEXP airTempSEXP, SEXP vpdSEXP, SEXP inputunitsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type airTemp(airTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vpd(vpdSEXP);
    Rcpp::traits::input_parameter< String >::type inputunits(inputunitsSEXP);
    rcpp_result_gen = Rcpp::wrap(calcRH_vpd_cpp(airTemp, vpd, inputunits));
    return rcpp_result_gen;
END_RCPP
}
// calcWB_cpp
NumericVector calcWB_cpp(NumericVector airTemp, NumericVector relativeHumidity, std::string inputunits, std::string outputunits, Nullable<std::string> method);
RcppExport SEXP _weathertools_calcWB_cpp(SEXP airTempSEXP, SEXP relativeHumiditySEXP, SEXP inputunitsSEXP, SEXP outputunitsSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type airTemp(airTempSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type relativeHumidity(relativeHumiditySEXP);
    Rcpp::traits::input_parameter< std::string >::type inputunits(inputunitsSEXP);
    Rcpp::traits::input_parameter< std::string >::type outputunits(outputunitsSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(calcWB_cpp(airTemp, relativeHumidity, inputunits, outputunits, method));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_weathertools_calcDewpoint_cpp", (DL_FUNC) &_weathertools_calcDewpoint_cpp, 5},
    {"_weathertools_calcHI_parallel", (DL_FUNC) &_weathertools_calcHI_parallel, 2},
    {"_weathertools_calcRH_cpp", (DL_FUNC) &_weathertools_calcRH_cpp, 3},
    {"_weathertools_calcRH_vpd_cpp", (DL_FUNC) &_weathertools_calcRH_vpd_cpp, 3},
    {"_weathertools_calcWB_cpp", (DL_FUNC) &_weathertools_calcWB_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_weathertools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
